Dynamically add kong.yml with luajit

diff --git a/bin/app/heroku-buildpack-kong-release b/bin/app/heroku-buildpack-kong-release
--- a/bin/app/heroku-buildpack-kong-release
+++ b/bin/app/heroku-buildpack-kong-release
@@ -1,18 +1,18 @@
 #!/usr/bin/env bash
 set -eu
 
-echo "Checking connection to Postgres database"
-database_fails=1
-while ! psql $DATABASE_URL --quiet --output /dev/null -c "SELECT 1"
-do
-  if [ "$database_fails" -eq "31" ]; then
-    echo "$(date -u) Connection to Postgres database could not be established within 15-minutes"
-    exit 2
-  else
-    echo "$(date -u) Attempt ${database_fails}/30: Postgres database not yet available"
-    sleep 30
-    database_fails=$[$database_fails +1]
-  fi
+# echo "Checking connection to Postgres database"
+# database_fails=1
+# while ! psql $DATABASE_URL --quiet --output /dev/null -c "SELECT 1"
+# do
+#   if [ "$database_fails" -eq "31" ]; then
+#     echo "$(date -u) Connection to Postgres database could not be established within 15-minutes"
+#     exit 2
+#   else
+#     echo "$(date -u) Attempt ${database_fails}/30: Postgres database not yet available"
+#     sleep 30
+#     database_fails=$[$database_fails +1]
+#   fi
 done
 
 if [ -x "bin/prerelease" ]
@@ -21,5 +21,5 @@ then
   ./bin/prerelease
 fi
 
-kong migrations bootstrap -c $KONG_CONF
-kong migrations up -c $KONG_CONF && kong migrations finish -c $KONG_CONF $@
+# kong migrations bootstrap -c $KONG_CONF
+# kong migrations up -c $KONG_CONF && kong migrations finish -c $KONG_CONF $@
